workflows:
    native-android:
        name: Native android
        max_build_duration: 120
        instance_type: windows_x2
        environment:
          android_signing:
            - davidKeystore
          groups:
            - google_play_credentials
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic7"
          java: 17
        scripts:
        - name: Set Android SDK location
          script: | 
             echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
        - name: Build Android release
          script: | 
            $PACKAGE_NAME="io.codemagic.dtrdic7"
            $LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name $PACKAGE_NAME)

            if ([string]::IsNullOrEmpty($LATEST_GOOGLE_PLAY_BUILD_NUMBER)) {
                # fallback in case no build number was found from Google Play.
                # Alternatively, you can `exit 1` to fail the build
                # BUILD_NUMBER is a Codemagic built-in variable tracking the number
                # of times this workflow has been built
                $UPDATED_BUILD_NUMBER=$env:BUILD_NUMBER
            }
            else {
                $UPDATED_BUILD_NUMBER=([int]$LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1)
            }
            .\gradlew bundleRelease `
                -PversionCode=$UPDATED_BUILD_NUMBER `
                -PversionName=1.0.$UPDATED_BUILD_NUMBER
        artifacts:
          - app/build/outputs/**/*.aab
        publishing: 
            email:
              recipients:
                - david@nevercode.io
              notify:
                success: true
                failure: false
            google_play:
              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
              track: internal
              submit_as_draft: true