workflows:
    native-android:
        name: Native android
        max_build_duration: 120
        instance_type: windows_x2
        environment:
          android_signing:
            - davidKeystore
          groups:
            - google_play_credentials
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic7"
          java: 17
        scripts:
        - name: Set Android SDK location
          script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
        - name: Build Android release
          script: | 
            LATEST_BUILD_NUMBER=$(google-play get-latest-build-number --package-name 'io.codemagic.dtrdic3')
            NEXT_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
            cd android
            ./gradlew bundleRelease --build-name=1.0.$NEXT_BUILD_NUMBER --build-number=$NEXT_BUILD_NUMBER

        artifacts:
          - app/build/outputs/**/*.aab
        publishing: 
            email:
              recipients:
                - david@nevercode.io
              notify:
                success: true
                failure: false
            google_play:
              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
              track: internal
              submit_as_draft: true