workflows:
    native-android:
        name: Native android
        max_build_duration: 120
        instance_type: linux_x2
        environment:
          android_signing:
            - davidKeystore
          groups:
            - google_play_credentials 
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic7" 
          java: 19
        triggering:
          events:
              - pull_request
              - push
          branch_patterns:
          - pattern: "main"
            include: true
            source: false
          - pattern: "dev"
            include: true
            source: false
        scripts:
        - name: Set Android SDK location
          script: | 
             echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

        - name: Build Android release
          script: | 
            cd android
              ./gradlew assembleRelease
        artifacts:
          - app/build/outputs/**/*.aab

        publishing: 
            email:
              recipients:
                - david@nevercode.io
              notify:
                success: true
                failure: false
            google_play:
              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
              track: internal
              submit_as_draft: true