workflows:
    native-android:
        name: Native android 
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
          android_signing:
            - davidKeystore
          groups:
            - google_play_credentials 
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic7" 
          java: 17

        triggering:
          events:
              - pull_request
              - push
          branch_patterns:
          - pattern: "main"
            include: true
            source: false
          - pattern: "dev"
            include: true
            source: false
        scripts:
          - name: show gradle info
            script: gradle --version
          - name: build apk with flutter
            script: flutter build apk --release
        artifacts:
          - build/app/outputs/apk/**/*.apk
        publishing:
          scripts:
            - name: publish to Github
              script: | 
                #!/usr/bin/env zsh
                
                echo "show GITHUB_TOKEN : ${GITHUB_TOKEN}"
                gh auth login ${GITHUB_TOKEN}
                gh release create "${CM_COMMIT}" \
                --title "Sudoku-Flutter#${CM_COMMIT} codemagic build" \
                --notes-file build/app/outputs/apk/**/*.apk
