workflows:
    native-android:
        name: Native android
        max_build_duration: 120
        instance_type: linux_x2
        environment:
          android_signing:
            - davidKeystore
          groups:
            - google_play_credentials 
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic7" 
          java: 19
        triggering:
          events:
              - pull_request
              - push
          branch_patterns:
          - pattern: "main"
            include: true
            source: false
          - pattern: "dev"
            include: true
            source: false


        artifacts:
          - app/build/outputs/**/*.aab
          - app/build/outputs/**/*.apk

        publishing: 
            email:
              recipients:
                - david@nevercode.io
              notify:
                success: true
                failure: false
            google_play:
              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
              track: testingtrack
              submit_as_draft: true
