workflows:
    native-android:
        name: Native android
        max_build_duration: 120
        instance_type: windows_x2
        environment:
          android_signing:
            - davidKeystore
          groups:
            - google_play_credentials 
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic7" 
          java: 19
        triggering:
          events:
              - pull_request
              - push
          branch_patterns:
          - pattern: "main"
            include: true
            source: false
          - pattern: "dev"
            include: true
            source: false
        scripts:
        - name: Set Android SDK location
          script: | 
             echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

        - name: Build Android release
          script: | 
            set PACKAGE_NAME=io.codemagic.dtrdic7

            set LATEST_GOOGLE_PLAY_BUILD_NUMBER=
            for /f "tokens=*" %%a in ('google-play get-latest-build-number --package-name "%PACKAGE_NAME%"') do set LATEST_GOOGLE_PLAY_BUILD_NUMBER=%%a

            if "%LATEST_GOOGLE_PLAY_BUILD_NUMBER%"=="" (
                rem fallback in case no build number was found from Google Play.
                rem Alternatively, you can `exit /b 1` to fail the build
                rem BUILD_NUMBER is a Codemagic built-in variable tracking the number
                rem of times this workflow has been built
                set UPDATED_BUILD_NUMBER=%BUILD_NUMBER%
            ) else (
                set /a UPDATED_BUILD_NUMBER=%LATEST_GOOGLE_PLAY_BUILD_NUMBER% + 1
            )

            cd %CM_BUILD_DIR%\android
            gradlew.bat bundleRelease ^
                -PversionCode=%UPDATED_BUILD_NUMBER% ^
                -PversionName=1.0.%UPDATED_BUILD_NUMBER%
        artifacts:
          - app/build/outputs/**/*.aab

        publishing: 
            email:
              recipients:
                - david@nevercode.io
              notify:
                success: true
                failure: false
            google_play:
              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
              track: internal
              submit_as_draft: true