definitions: 
  instance_linux_x2: &instance_linux_x2
    instance_type: linux_x2
    max_build_duration: 120
  env_versions: &env_versions
    java: 19
  scripts: 
    - &pre-defined-steps
      name: Set Android SDK location
      script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
    - &build-android-release
      name: Build Android release
      script: | 
        LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
        if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
          # fallback in case no build number was found from Google Play.
          # Alternatively, you can `exit 1` to fail the build
          # BUILD_NUMBER is a Codemagic built-in variable tracking the number
          # of times this workflow has been built
            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
        else
            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
            [--tracks testingtrack]
        fi
        cd $CM_BUILD_DIR/android
        ./gradlew bundleRelease \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.0.$UPDATED_BUILD_NUMBER

workflows:
    native-android:
        name: Native android
        max_build_duration: 120
        instance_type: linux_x2
        environment:
          android_signing:
            - davidKeystore
          groups:
            - google_play_credentials 
          vars:
            PACKAGE_NAME: "io.codemagic.dtrdic7" 
          java: 19
        triggering:
          events:
              - pull_request
              - push
          branch_patterns:
          - pattern: "main"
            include: true
            source: false
          - pattern: "dev"
            include: true
            source: false


        scripts:
        - *pre-defined-steps
        - *build-android-release

        artifacts:
          - app/build/outputs/**/*.aab
          - app/build/outputs/**/*.apk

        publishing: 
            email:
              recipients:
                - david@nevercode.io
              notify:
                success: true
                failure: false
            google_play:
              credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
              track: testingtrack
              submit_as_draft: true
